# taps
tap "homebrew/cask-fonts"
brew "mas"
tap "pvinis/pvinis"

# base
brew "git"
brew "stow"

# shell
brew "zsh"
brew "thefuck"
brew "trash"

# brew "ag"
#brew "fzf"

# ruby 
brew "chruby"
brew "ruby-install"

# brew "yarn", args: ["without-node"]
brew "nodenv"
brew "colortools"

cask "keepingyouawake"

# messaging
cask "franz"
#cask "rambox"

# dev

mas "xcode", id: 497799835


cask "visual-studio-code"
#cask "react-native-debugger"
#cask "docker"

cask "webtorrent"
#cask "teamviewer"
cask "save-hollywood"
#cask "postman"

cask "the-unarchiver"


#cask "arq"
cask "skype"
cask "spotify"
cask "steam"
cask "vlc"
#cask "tunnelblick"
cask "caskroom/versions/dropbox-beta"
#cask "caskroom/versions/firefox-beta"
#cask "caskroom/versions/google-chrome-beta"
cask "caskroom/versions/1password-beta"
cask "caskroom/versions/airmail-beta"
#cask "caskroom/versions/iterm2-nightly"
#cask "vnc-viewer"

# fonts
cask "font-iosevka"

# mas
mas "paste", id: 967805235
mas "magnet", id: 441258766
